export const projects = [
    {
    title: 'Speakwise',
    description: "A voice-driven AI tutor that lets you learn any subject through natural conversation—ask questions, get instant explanations, and receive personalized guidance anytime, hands-free.",
      image: '/images/Speakwise.png',
      tags: ['NextJs', 'Cleark Auth', 'Vapi'],
    source: 'http://speakwise.vercel.app',
    visit: 'https://github.com/ayush200998/Speakwise',
    id: 1,
  },
  {
    title: 'Brainstormer',
    description: "A platform designed to spark creativity through visual brainstorming. Easily construct illustrative diagrams to map out your ideas and simultaneously capture essential notes, ensuring a comprehensive and organized thought process.",
      image: '/images/Brainstormer.png',
      tags: ['NextJs', 'Excalidraw', 'Kinde', 'EditorJs'],
    source: 'https://brainstormer-virid.vercel.app',
    visit: 'https://github.com/ayush200998/Brainstormer',
    id: 2,
  },
  {
    title: 'Lingo',
    description: "An engaging, interactive app that makes language learning fun with hands-on activities and real-time feedback.",
      image: '/images/Lingo.png',
      tags: ['NextJs', 'Clerk Auth', 'Stripe'],
    source: 'https://lingo-wheat-one.vercel.app/learn',
    visit: 'https://github.com/ayush200998/Lingo',
    id: 3,
  },
  {
    title: 'Room',
    description: "A video conferencing application build using NextJs",
      image: '/images/Room.png',
      tags: ['NextJs', 'Stream Io', 'Clerk Auth',],
    source: 'https://dbzoom-ayush200998s-projects.vercel.app',
    visit: 'https://github.com/ayush200998/dbzoom',
    id: 4,
  },
  {
    title: 'Memories App',
    description: "A MERN stack Application by which user can post, update, delete a particular memory. It uses Google Auth.",
      image: '/images/Memories.png',
      tags: ['MERN Stack', 'Redux', 'Google Auth',],
    source: 'https://memories-aps.netlify.app/',
    visit: 'https://github.com/ayush200998/MemoriesApp',
    id: 5,
  },
  {
    title: 'Expense Tracker',
    description: "An Application used to manage user expenses, user can also add their expenses using voice command. It shows all the expense data Graphically.",
      image: '/images/Expense.png',
      tags: ['React', 'Context', 'Speechly', 'ChartJs', 'Netlify'],
    source: 'https://elegant-cray-a3790f.netlify.app/',
    visit: 'https://github.com/ayush200998/Expense-Tracker',
    id: 6,
  },
  // Deprecated Projects ------------------------------------
  {
    title: 'Blogging Website',
    description: "A basic Blogging website where users can share their blogs, Users can also follow other users, A Global chat Application is also present where users can chat with each other. ",
      image: '/images/Blogging.png',
      tags: ['Javascript', 'NodeJs', 'MongoDb'],
    source: 'https://github.com/ayush200998/BloggingApp',
    visit: 'https://github.com/ayush200998/BloggingApp',
    id: 7,
  },
  {
    title: 'Messenger App',
    description: "A global chat application in which users can chat with other users.",
    image: '/images/Messenger.png',
    tags: ['React', 'Firebase'],
    source: 'https://facebook-messenger-b37ea.web.app/',
    visit: 'https://github.com/ayush200998/Messenger_app',
    id: 8,
  },
  {
    title: 'Hulu',
    description: "An application which provide movie lists to the users according to the Genre selected.",
    image: '/images/Hulu.png',
    tags: ['React', 'Firebase', 'NextJs', 'TMDB'],
    source: 'https://hulu-2-0-green.vercel.app/',
    visit: 'https://github.com/ayush200998/Hulu_2.0',
    id: 9,
  },
  {
    title: 'Keeper',
    description: "A Todo list web app by which a user can keep a record of things he wants.",
    image: '/images/Keeper.png',
    tags: ['React'],
    source: 'https://codesandbox.io/s/9uuwh',
    visit: 'https://codesandbox.io/s/9uuwh',
    id: 10,
  },
  {
    title: 'Netflix Clone',
    description: "A Web app which shows list of movies to the user according to the Genre,It uses Email-password Authentication,The App is build using ReactJs and Firebase.",
      image: '/images/Netflix.png',
      tags: ['Firebase','React', 'Redux'],
    source: 'https://netflixclone-3c963.web.app/',
    visit: 'https://github.com/ayush200998/Netflix-Clone',
    id: 11,
  },
  {
    title: 'Instagram Clone',
    description:"A Social media web app which allows users to post pictures, share their comments on other users pics.",
    image: '/images/Insta.png',
    tags: ['React', 'Firebase'],
    source: 'https://finstagram-91090.web.app/',
    visit: 'https://github.com/ayush200998/Finstagram',
    id: 12,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey with learning C Programming', },
  { year: 2018, text: 'Worked on different things and learning new Programmings concepts and Programming Languages', },
  { year: 2019, text: 'Started JavaScript by making small Projects.', },
  { year: 2020, text: 'Started React and made a lots of Projects with it.', },
  { year: 2021, text: 'Learning more and more frameworks to master the Back-End as well as Front-End.', },
  { year: 2022, text: 'Started development journey with Tweeny Technologies as a Full stack developer', },
];