export const projects = [
  {
    title: 'Netflix Clone',
    description: "A Web app which shows list of movies to the user according to the Genre,It uses Email-password Authentication,The App is build using ReactJs and Firebase.",
      image: '/images/Netflix.png',
      tags: ['Firebase','React', 'Redux'],
    source: 'https://netflixclone-3c963.web.app/',
    visit: 'https://github.com/ayush200998/Netflix-Clone',
    id: 0,
  },
  {
    title: 'Instagram Clone',
    description:"A Social media web app which allows users to post pictures, share their comments on other users pics.",
    image: '/images/Insta.png',
    tags: ['React', 'Firebase'],
    source: 'https://finstagram-91090.web.app/',
    visit: 'https://github.com/ayush200998/Finstagram',
    id: 1,
  },
  {
    title: 'Blogging Website',
    description: "A basic Blogging website where users can share their blogs, Users can also follow other users, A Global chat Application is also present where users can chat with each other. ",
      image: '/images/Blogging.png',
      tags: ['Javascript', 'NodeJs', 'MongoDb'],
    source: 'https://github.com/ayush200998/BloggingApp',
    visit: 'https://github.com/ayush200998/BloggingApp',
    id: 2,
  },
  {
    title: 'Messenger App',
    description: "A global chat application in which users can chat with other users.",
    image: '/images/Messenger.png',
    tags: ['React', 'Firebase'],
    source: 'https://facebook-messenger-b37ea.web.app/',
    visit: 'https://github.com/ayush200998/Messenger_app',
    id: 3,
  },
  {
    title: 'Hulu',
    description: "An application which provide movie lists to the users according to the Genre selected.",
    image: '/images/Hulu.png',
    tags: ['React', 'Firebase', 'NextJs', 'TMDB'],
    source: 'https://hulu-2-0-green.vercel.app/',
    visit: 'https://github.com/ayush200998/Hulu_2.0',
    id: 4,
  },
  {
    title: 'Keeper',
    description: "A Todo list web app by which a user can keep a record of things he wants.",
    image: '/images/Keeper.png',
    tags: ['React'],
    source: 'https://codesandbox.io/s/9uuwh',
    visit: 'https://codesandbox.io/s/9uuwh',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey with learning C Programming', },
  { year: 2018, text: 'Working on different things and learning new Programmings concepts and Programming Languages', },
  { year: 2019, text: 'Started JavaScript by making small Projects.', },
  { year: 2020, text: 'Started React and made a lots of Projects with it.', },
  { year: 2021, text: 'Learning more and more frameworks to master the Back-End as well as Front-End.', },
];